document.addEventListener("DOMContentLoaded", function () {
    const welcomeScreen = document.getElementById("welcomeScreen");
    const mainContent = document.getElementById("mainContent");
    const form = document.getElementById("workoutForm");
    const planDetails = document.getElementById("planDetails");
    const workoutPlanDiv = document.getElementById("workoutPlan");
    const controlButtons = document.getElementById("controlButtons");
    const stopButton = document.getElementById("stopButton");
    const resumeButton = document.getElementById("resumeButton");
    const clearButton = document.getElementById("clearButton");

    let workoutPlan = [];
    let isGenerating = false;
    let stopGeneration = false;
    let currentStep = 0;

    // Show the main content after a delay (e.g., 3 seconds)
    setTimeout(() => {
        welcomeScreen.classList.add("hidden");
        mainContent.classList.remove("hidden");
    }, 3000);

    // Toggle height input fields based on selected unit
    document.getElementById("heightUnit").addEventListener("change", function () {
        const heightUnit = this.value;
        if (heightUnit === "cm") {
            document.getElementById("heightCmDiv").classList.remove("hidden");
            document.getElementById("heightFtInDiv").classList.add("hidden");
        } else {
            document.getElementById("heightCmDiv").classList.add("hidden");
            document.getElementById("heightFtInDiv").classList.remove("hidden");
        }
    });

    // Handle form submission and generate workout plan
    form.addEventListener("submit", function (event) {
        event.preventDefault();

        // Retrieve user inputs
        const gender = document.getElementById("gender").value;
        const age = parseInt(document.getElementById("age").value, 10);
        const heightUnit = document.getElementById("heightUnit").value;
        const heightCm = parseInt(document.getElementById("height").value, 10);
        const feet = parseInt(document.getElementById("feet").value, 10) || 0;
        const inches = parseInt(document.getElementById("inches").value, 10) || 0;
        const experience = document.getElementById("experience").value;
        const goals = document.getElementById("goals").value;
        const frequency = document.getElementById("frequency").value;

        console.log("Form submitted with:", { gender, age, heightUnit, heightCm, feet, inches, experience, goals, frequency });

        // Clear previous error messages
        document.getElementById("ageError").textContent = "";
        document.getElementById("heightError").textContent = "";

        // Validation
        let isValid = true;

       if (age < 17) {
    document.getElementById("ageError").textContent = "You must be 17 or older.";
    isValid = false;
} else if (age > 100) {
    document.getElementById("ageError").textContent = "Age must be 100 or younger.";
    isValid = false;
} else {
    document.getElementById("ageError").textContent = ""; // Clear the error message if age is valid
}


        let heightInCm = heightCm;
        if (heightUnit === "ft-in") {
            heightInCm = (feet * 30.48) + (inches * 2.54);
            if (feet < 4 || feet > 7 || inches < 0 || inches > 11) {
                document.getElementById("heightFtInError").textContent = "Height must be between 4'0\" and 7'0\".";
                isValid = false;
            }
        } else if (heightUnit === "cm") {
            if (heightCm < 122 || heightCm > 213) {
                document.getElementById("heightError").textContent = "Height must be between 122 cm and 213 cm.";
                isValid = false;
            }
        }

        if (!isValid) {
            console.log("Validation failed.");
            return; // Stop processing if validation fails
        }

        console.log("Validation passed.");

        if (experience === "0" && goals === "gain muscle" && frequency === "3") {
            workoutPlan = [
                "Day 1: Upper Body",
                "Warm-up: 5 minutes of light cardio (e.g., jogging or cycling)",
                "Exercises:",
                "Bench Press: 3 sets of 10 reps",
                "Dumbbell Rows: 3 sets of 12 reps",
                "Overhead Dumbbell Press: 3 sets of 10 reps",
                "Bicep Curls: 3 sets of 12 reps",
                "Tricep Dips: 3 sets of 10 reps",
                "Cool Down: 5 minutes of stretching",
                "Duration: Approximately 45 minutes",
                "",
                "Day 2: Lower Body",
                "Warm-up: 5 minutes of light cardio",
                "Exercises:",
                "Squats: 3 sets of 10 reps",
                "Lunges: 3 sets of 12 reps per leg",
                "Leg Press: 3 sets of 10 reps",
                "Calf Raises: 3 sets of 15 reps",
                "Hamstring Curls: 3 sets of 12 reps",
                "Cool Down: 5 minutes of stretching",
                "Duration: Approximately 45 minutes",
                "",
                "Day 3: Full Body",
                "Warm-up: 5 minutes of light cardio",
                "Exercises:",
                "Deadlifts: 3 sets of 10 reps",
                "Push-ups: 3 sets of 12 reps",
                "Pull-ups or Lat Pulldowns: 3 sets of 10 reps",
                "Leg Raises: 3 sets of 15 reps",
                "Planks: 3 sets of 30 seconds",
                "Cool Down: 5 minutes of stretching",
                "Duration: Approximately 45 minutes",
                "",
                "Summary:",
                `Workout Days: ${frequency} times a week`,
                "Duration per Session: ~45 minutes"
            ];
        } else if (experience === "0" && goals === "lose weight" && frequency === "3") {
            workoutPlan = [
               
                "Day 1: Full Body Circuit",
                "Warm-up: 5 minutes of brisk walking or light jogging",
                "Exercises:",
                "Bodyweight Squats: 3 sets of 15 reps",
                "Push-ups (Knee or Standard): 3 sets of 12 reps",
                "Dumbbell Rows (or Bent Over Rows with No Weights): 3 sets of 12 reps per side",
                "Glute Bridges: 3 sets of 15 reps",
                "Plank: 3 sets of 20 seconds",
                "Cool Down: 5 minutes of stretching",
                "Duration: Approximately 40 minutes",
                "",
                "Day 2: Cardio & Core",
                "Warm-up: 5 minutes of brisk walking or light jogging",
                "Exercises:",
                "Jumping Jacks: 3 sets of 30 seconds",
                "Mountain Climbers: 3 sets of 20 reps per leg",
                "High Knees: 3 sets of 30 seconds",
                "Russian Twists: 3 sets of 20 reps per side",
                "Leg Raises: 3 sets of 12 reps",
                "Bicycle Crunches: 3 sets of 15 reps per side",
                "Cool Down: 5 minutes of stretching",
                "Duration: Approximately 40 minutes",
                "",
                "Day 3: Strength & Cardio Mix",
                "Warm-up: 5 minutes of brisk walking or light jogging",
                "Exercises:",
                "Lunges: 3 sets of 12 reps per leg",
                "Dumbbell Shoulder Press: 3 sets of 12 reps",
                "Burpees: 3 sets of 10 reps",
                "Step-Ups: 3 sets of 15 reps per leg (use a stable bench or platform)",
                "Plank with Shoulder Taps: 3 sets of 20 taps",
                "Cool Down: 5 minutes of stretching",
                "Duration: Approximately 40 minutes",
                "",
                "Summary:",
                `Workout Days: ${frequency} times a week`,
                "Duration per Session: ~40 minutes"
              ];
        } else if (experience === "0" && goals === "look shredded" && frequency === "4") {
           workoutPlan = [
        
        "Day 1: Upper Body & Core",
        "Warm-up: 5 minutes of light cardio (e.g., jumping jacks or brisk walking)",
        "Exercises:",
        "Push-ups: 3 sets of 12 reps",
        "Bent Over Rows: 3 sets of 12 reps",
        "Dumbbell Shoulder Press: 3 sets of 12 reps",
        "Bicep Curls: 3 sets of 15 reps",
        "Tricep Dips: 3 sets of 15 reps",
        "Plank: 3 sets of 30 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Lower Body & Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 3 sets of 15 reps",
        "Lunges: 3 sets of 12 reps per leg",
        "Leg Press: 3 sets of 15 reps",
        "Romanian Deadlifts: 3 sets of 12 reps",
        "Calf Raises: 3 sets of 20 reps",
        "Russian Twists: 3 sets of 20 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Full Body & Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Burpees: 3 sets of 10 reps",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Mountain Climbers: 3 sets of 20 reps per leg",
        "Push-ups: 3 sets of 15 reps",
        "Plank with Shoulder Taps: 3 sets of 20 reps",
        "Jump Squats: 3 sets of 15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 4: HIIT & Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "High Knees: 3 sets of 30 seconds",
        "Jumping Jacks: 3 sets of 30 seconds",
        "Lunges: 3 sets of 15 reps per leg",
        "Bicycle Crunches: 3 sets of 20 reps per side",
        "Leg Raises: 3 sets of 15 reps",
        "Plank: 3 sets of 30 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 40-45 minutes",
        "",
        "Summary:",
        `Workout Days: ${frequency} times a week`,
        "Duration per Session: ~40-50 minutes"
       ];
              
          
        } else if (experience === "0" && goals === "gain muscle" && frequency === "4") {
    workoutPlan = [
   
        "Day 1: Upper Body",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jogging)",
        "Exercises:",
        "Bench Press: 3 sets of 10 reps",
        "Dumbbell Rows: 3 sets of 10 reps per side",
        "Overhead Dumbbell Press: 3 sets of 12 reps",
        "Bicep Curls: 3 sets of 12 reps",
        "Tricep Dips: 3 sets of 10 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Lower Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 3 sets of 12 reps",
        "Lunges: 3 sets of 12 reps per leg",
        "Leg Press: 3 sets of 12 reps",
        "Romanian Deadlifts: 3 sets of 10 reps",
        "Calf Raises: 3 sets of 15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Upper Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Incline Dumbbell Press: 3 sets of 10 reps",
        "Lat Pulldowns: 3 sets of 12 reps",
        "Dumbbell Bench Press: 3 sets of 12 reps",
        "Seated Dumbbell Press: 3 sets of 12 reps",
        "Hammer Curls: 3 sets of 12 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 4: Lower Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 3 sets of 10 reps",
        "Leg Extensions: 3 sets of 12 reps",
        "Hamstring Curls: 3 sets of 12 reps",
        "Bulgarian Split Squats: 3 sets of 12 reps per leg",
        "Standing Calf Raises: 3 sets of 15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        `Workout Days: ${frequency} times a week`,
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "0" && goals === "gain muscle" && frequency === "5") {
    workoutPlan = [
        "Day 1: Chest & Triceps",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jogging)",
        "Exercises:",
        "Bench Press: 4 sets of 10 reps",
        "Incline Dumbbell Press: 4 sets of 12 reps",
        "Chest Flyes: 3 sets of 12 reps",
        "Tricep Dips: 3 sets of 10 reps",
        "Tricep Pushdowns: 3 sets of 12 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 2: Back & Biceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Lat Pulldowns: 4 sets of 12 reps",
        "Bent Over Rows: 4 sets of 10 reps",
        "Seated Rows: 3 sets of 12 reps",
        "Bicep Curls: 3 sets of 12 reps",
        "Hammer Curls: 3 sets of 12 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 3: Legs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 12 reps",
        "Leg Press: 4 sets of 12 reps",
        "Lunges: 3 sets of 12 reps per leg",
        "Romanian Deadlifts: 3 sets of 12 reps",
        "Calf Raises: 4 sets of 15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 4: Shoulders & Abs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Dumbbell Shoulder Press: 4 sets of 12 reps",
        "Lateral Raises: 3 sets of 15 reps",
        "Front Raises: 3 sets of 12 reps",
        "Rear Delt Flyes: 3 sets of 12 reps",
        "Plank: 3 sets of 45 seconds",
        "Russian Twists: 3 sets of 20 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 5: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 10 reps",
        "Push-ups: 3 sets of 15 reps",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Dumbbell Rows: 3 sets of 12 reps per side",
        "Leg Raises: 3 sets of 15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Summary:",
        `Workout Days: ${frequency} times a week`,
        "Duration per Session: ~50-55 minutes"
    ];
} else if (experience === "0" && goals === "look shredded" && frequency === "5") {
    workoutPlan = [
        "Day 1: Upper Body",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jogging)",
        "Exercises:",
        "Bench Press: 4 sets of 10 reps",
        "Incline Dumbbell Press: 4 sets of 12 reps",
        "Dumbbell Rows: 4 sets of 12 reps per side",
        "Shoulder Press: 3 sets of 12 reps",
        "Tricep Dips: 3 sets of 12 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 2: Lower Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 12 reps",
        "Lunges: 4 sets of 12 reps per leg",
        "Leg Press: 3 sets of 12 reps",
        "Romanian Deadlifts: 3 sets of 12 reps",
        "Calf Raises: 4 sets of 15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 3: Full Body & Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Burpees: 3 sets of 15 reps",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Mountain Climbers: 3 sets of 30 seconds",
        "Push-ups: 3 sets of 15 reps",
        "Plank: 3 sets of 45 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45 minutes",
        "",
        "Day 4: Upper Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-ups: 4 sets of 8 reps",
        "Incline Bench Press: 4 sets of 12 reps",
        "Dumbbell Flyes: 3 sets of 12 reps",
        "Lateral Raises: 3 sets of 15 reps",
        "Bicep Curls: 3 sets of 12 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 5: Lower Body & Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 10 reps",
        "Leg Extensions: 3 sets of 15 reps",
        "Hamstring Curls: 3 sets of 15 reps",
        "Bulgarian Split Squats: 3 sets of 12 reps per leg",
        "Russian Twists: 3 sets of 20 reps per side",
        "Leg Raises: 3 sets of 15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Summary:",
        `Workout Days: ${frequency} times a week`,
        "Duration per Session: ~45-50 minutes"
    ];
}else if (experience === "0" && goals === "lose weight" && frequency === "4") {
    workoutPlan = [
        "Day 1: Full Body + Cardio",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jogging)",
        "Exercises:",
        "Squats: 3 sets of 15 reps",
        "Push-ups: 3 sets of 12 reps",
        "Dumbbell Rows: 3 sets of 12 reps per side",
        "Lunges: 3 sets of 12 reps per leg",
        "Plank: 3 sets of 45 seconds",
        "Cardio: 20 minutes of moderate-intensity cardio (e.g., cycling, brisk walking)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 2: Upper Body + Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 3 sets of 12 reps",
        "Dumbbell Shoulder Press: 3 sets of 12 reps",
        "Lat Pulldowns: 3 sets of 12 reps",
        "Bicep Curls: 3 sets of 15 reps",
        "Tricep Dips: 3 sets of 12 reps",
        "Cardio: 20 minutes of HIIT (e.g., alternating sprints with walking)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 3: Lower Body + Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 3 sets of 12 reps",
        "Leg Press: 3 sets of 15 reps",
        "Leg Curls: 3 sets of 15 reps",
        "Calf Raises: 3 sets of 20 reps",
        "Mountain Climbers: 3 sets of 30 seconds",
        "Cardio: 20 minutes of moderate-intensity cardio",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 4: Full Body + Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Burpees: 3 sets of 12 reps",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Bodyweight Squats: 3 sets of 15 reps",
        "Push-ups: 3 sets of 12 reps",
        "Plank: 3 sets of 45 seconds",
        "Cardio: 20 minutes of HIIT (e.g., alternating high-intensity exercises with short rest periods)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Summary:",
        `Workout Days: 4 times a week`,
        "Duration per Session: ~50 minutes"
    ];

} else if (experience === "0" && goals === "lose weight" && frequency === "5") {
    workoutPlan = [
        "Day 1: Upper Body + Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 4 sets of 10 reps",
        "Dumbbell Rows: 4 sets of 10 reps per side",
        "Shoulder Press: 4 sets of 12 reps",
        "Bicep Curls: 3 sets of 12 reps",
        "Tricep Dips: 3 sets of 10 reps",
        "Cardio: 15 minutes of moderate-intensity cardio (e.g., brisk walking, cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 2: Lower Body + Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 12 reps",
        "Lunges: 4 sets of 12 reps per leg",
        "Leg Press: 4 sets of 12 reps",
        "Romanian Deadlifts: 4 sets of 10 reps",
        "Calf Raises: 4 sets of 15 reps",
        "Cardio: 15 minutes of HIIT (e.g., alternating sprints and walking)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 3: Full Body + Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 10 reps",
        "Push-ups: 3 sets of 15 reps",
        "Kettlebell Swings: 4 sets of 15 reps",
        "Mountain Climbers: 3 sets of 30 seconds",
        "Plank: 3 sets of 45 seconds",
        "Cardio: 15 minutes of moderate-intensity cardio",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 4: Upper Body + Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Incline Bench Press: 4 sets of 10 reps",
        "Lat Pulldowns: 4 sets of 12 reps",
        "Dumbbell Flyes: 3 sets of 12 reps",
        "Lateral Raises: 3 sets of 15 reps",
        "Hammer Curls: 3 sets of 12 reps",
        "Cardio: 15 minutes of HIIT",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 5: Lower Body + Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 10 reps",
        "Leg Extensions: 4 sets of 15 reps",
        "Hamstring Curls: 4 sets of 15 reps",
        "Bulgarian Split Squats: 3 sets of 12 reps per leg",
        "Russian Twists: 3 sets of 20 reps per side",
        "Leg Raises: 3 sets of 15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Summary:",
        `Workout Days: 5 times a week`,
        "Duration per Session: ~55 minutes"

    ];
} else if (experience === "6-12" && goals === "gain muscle" && frequency === "3") {
    workoutPlan = [
        "Day 1: Upper Body",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jogging)",
        "Exercises:",
        "Bench Press: 4 sets of 8-10 reps",
        "Dumbbell Rows: 4 sets of 8-10 reps per side",
        "Shoulder Press: 3 sets of 10-12 reps",
        "Bicep Curls: 3 sets of 12-15 reps",
        "Tricep Dips: 3 sets of 10-12 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 2: Lower Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 8-10 reps",
        "Leg Press: 4 sets of 10-12 reps",
        "Lunges: 3 sets of 12 reps per leg",
        "Romanian Deadlifts: 3 sets of 10-12 reps",
        "Calf Raises: 4 sets of 15-20 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 3: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 8-10 reps",
        "Push-ups: 3 sets of 12-15 reps",
        "Kettlebell Swings: 3 sets of 12-15 reps",
        "Lat Pulldowns: 3 sets of 10-12 reps",
        "Plank: 3 sets of 45-60 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~50 minutes"
    ];
  
  } else if (experience === "6-12" && goals === "gain muscle" && frequency === "4") {
    workoutPlan = [
        "Day 1: Chest and Triceps",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jogging)",
        "Exercises:",
        "Bench Press: 4 sets of 8-10 reps",
        "Incline Dumbbell Press: 4 sets of 10-12 reps",
        "Chest Flyes: 3 sets of 12-15 reps",
        "Tricep Dips: 3 sets of 10-12 reps",
        "Tricep Pushdowns: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 2: Back and Biceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-Ups: 4 sets of 8-10 reps",
        "Bent-Over Rows: 4 sets of 8-10 reps",
        "Lat Pulldowns: 3 sets of 10-12 reps",
        "Dumbbell Bicep Curls: 3 sets of 12-15 reps",
        "Hammer Curls: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 3: Legs and Abs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 8-10 reps",
        "Leg Press: 4 sets of 10-12 reps",
        "Romanian Deadlifts: 4 sets of 10-12 reps",
        "Leg Curls: 3 sets of 12-15 reps",
        "Calf Raises: 4 sets of 15-20 reps",
        "Leg Raises: 3 sets of 15 reps",
        "Plank: 3 sets of 45-60 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 4: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 8-10 reps",
        "Overhead Press: 4 sets of 8-10 reps",
        "Dumbbell Bench Press: 3 sets of 10-12 reps",
        "Dumbbell Rows: 3 sets of 10-12 reps",
        "Kettlebell Swings: 3 sets of 12-15 reps",
        "Russian Twists: 3 sets of 20 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Summary:",
        "Workout Days: 4 times a week",
        "Duration per Session: ~55-60 minutes"
    ];
      
} else if (experience === "6-12" && goals === "gain muscle" && frequency === "5") {
    workoutPlan = [
        "Day 1: Chest and Triceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 4 sets of 6-8 reps",
        "Incline Dumbbell Press: 4 sets of 8-10 reps",
        "Chest Flyes: 3 sets of 10-12 reps",
        "Cable Crossovers: 3 sets of 12-15 reps",
        "Skull Crushers: 3 sets of 8-10 reps",
        "Overhead Tricep Extensions: 3 sets of 10-12 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 2: Back and Biceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-Ups: 4 sets of 6-8 reps (add weight if needed)",
        "Bent-Over Barbell Rows: 4 sets of 8-10 reps",
        "Lat Pulldowns: 3 sets of 10-12 reps",
        "Single-Arm Dumbbell Rows: 3 sets of 10-12 reps per side",
        "Preacher Curls: 3 sets of 10-12 reps",
        "Concentration Curls: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 3: Legs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps",
        "Leg Press: 4 sets of 8-10 reps",
        "Bulgarian Split Squats: 3 sets of 10-12 reps per leg",
        "Romanian Deadlifts: 4 sets of 8-10 reps",
        "Leg Extensions: 3 sets of 12-15 reps",
        "Standing Calf Raises: 4 sets of 15-20 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 4: Shoulders and Abs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Overhead Press: 4 sets of 6-8 reps",
        "Arnold Press: 4 sets of 8-10 reps",
        "Lateral Raises: 3 sets of 12-15 reps",
        "Front Raises: 3 sets of 12-15 reps",
        "Reverse Pec Deck: 3 sets of 12-15 reps",
        "Hanging Leg Raises: 3 sets of 15 reps",
        "Cable Woodchoppers: 3 sets of 12-15 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 5: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 6-8 reps",
        "Dumbbell Bench Press: 4 sets of 8-10 reps",
        "Barbell Rows: 3 sets of 8-10 reps",
        "Leg Press: 3 sets of 10-12 reps",
        "Kettlebell Swings: 3 sets of 12-15 reps",
        "Plank with Shoulder Taps: 3 sets of 20 taps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~60 minutes"
    ];
} else if (experience === "6-12" && goals === "look shredded" && frequency === "3") {
    workoutPlan = [
        "Day 1: Upper Body",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jogging)",
        "Exercises:",
        "Bench Press: 4 sets of 8-10 reps",
        "Incline Dumbbell Press: 4 sets of 10-12 reps",
        "Dumbbell Rows: 4 sets of 8-10 reps",
        "Lat Pulldowns: 3 sets of 10-12 reps",
        "Lateral Raises: 3 sets of 12-15 reps",
        "Tricep Dips: 3 sets of 10-12 reps",
        "Cable Bicep Curls: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 2: Lower Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 8-10 reps",
        "Deadlifts: 4 sets of 8-10 reps",
        "Leg Press: 3 sets of 10-12 reps",
        "Leg Curls: 3 sets of 12-15 reps",
        "Leg Extensions: 3 sets of 12-15 reps",
        "Calf Raises: 4 sets of 15-20 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 3: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 8-10 reps",
        "Dumbbell Bench Press: 4 sets of 8-10 reps",
        "Pull-Ups: 3 sets of 8-10 reps",
        "Dumbbell Shoulder Press: 3 sets of 10-12 reps",
        "Kettlebell Swings: 3 sets of 12-15 reps",
        "Plank: 3 sets of 45-60 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~60 minutes"
    ];
} else if (experience === "6-12" && goals === "look shredded" && frequency === "4") {
    workoutPlan = [
        "Day 1: Chest and Triceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 4 sets of 8-10 reps",
        "Incline Dumbbell Press: 4 sets of 10-12 reps",
        "Chest Flyes: 3 sets of 12-15 reps",
        "Tricep Dips: 3 sets of 10-12 reps",
        "Skull Crushers: 3 sets of 10-12 reps",
        "Overhead Tricep Extensions: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 2: Back and Biceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-Ups: 4 sets of 8-10 reps",
        "Bent-Over Rows: 4 sets of 8-10 reps",
        "Lat Pulldowns: 3 sets of 10-12 reps",
        "Single-Arm Dumbbell Rows: 3 sets of 12 reps per side",
        "Barbell Bicep Curls: 3 sets of 10-12 reps",
        "Hammer Curls: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 3: Legs and Abs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 8-10 reps",
        "Leg Press: 4 sets of 10-12 reps",
        "Romanian Deadlifts: 3 sets of 10-12 reps",
        "Leg Curls: 3 sets of 12-15 reps",
        "Calf Raises: 4 sets of 15-20 reps",
        "Hanging Leg Raises: 3 sets of 15 reps",
        "Russian Twists: 3 sets of 20 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 4: Shoulders and Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Overhead Press: 4 sets of 8-10 reps",
        "Arnold Press: 3 sets of 10-12 reps",
        "Lateral Raises: 3 sets of 12-15 reps",
        "Front Raises: 3 sets of 12-15 reps",
        "Dumbbell Bench Press: 3 sets of 8-10 reps",
        "Kettlebell Swings: 3 sets of 12-15 reps",
        "Plank: 3 sets of 45-60 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Summary:",
        "Workout Days: 4 times a week",
        "Duration per Session: ~60 minutes"
    ];
} else if (experience === "6-12" && goals === "look shredded" && frequency === "5") {
    workoutPlan = [
        "Day 1: Chest and Triceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 4 sets of 8-10 reps",
        "Incline Dumbbell Press: 4 sets of 10-12 reps",
        "Chest Flyes: 3 sets of 12-15 reps",
        "Dips: 3 sets of 10-12 reps",
        "Skull Crushers: 3 sets of 10-12 reps",
        "Overhead Tricep Extensions: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 2: Back and Biceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-Ups: 4 sets of 8-10 reps",
        "Bent-Over Barbell Rows: 4 sets of 8-10 reps",
        "Lat Pulldowns: 3 sets of 10-12 reps",
        "Single-Arm Dumbbell Rows: 3 sets of 12 reps per side",
        "Barbell Bicep Curls: 3 sets of 10-12 reps",
        "Hammer Curls: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 3: Legs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 8-10 reps",
        "Leg Press: 4 sets of 10-12 reps",
        "Romanian Deadlifts: 3 sets of 10-12 reps",
        "Leg Curls: 3 sets of 12-15 reps",
        "Leg Extensions: 3 sets of 12-15 reps",
        "Calf Raises: 4 sets of 15-20 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 4: Shoulders and Abs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Overhead Press: 4 sets of 8-10 reps",
        "Arnold Press: 3 sets of 10-12 reps",
        "Lateral Raises: 3 sets of 12-15 reps",
        "Front Raises: 3 sets of 12-15 reps",
        "Reverse Pec Deck: 3 sets of 12-15 reps",
        "Hanging Leg Raises: 3 sets of 15 reps",
        "Cable Woodchoppers: 3 sets of 12-15 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 5: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 8-10 reps",
        "Dumbbell Bench Press: 4 sets of 8-10 reps",
        "Pull-Ups: 3 sets of 8-10 reps",
        "Kettlebell Swings: 3 sets of 12-15 reps",
        "Dumbbell Lunges: 3 sets of 10-12 reps per leg",
        "Plank with Shoulder Taps: 3 sets of 20 taps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~60 minutes"
    ];
} else if (experience === "6-12" && goals === "lose weight" && frequency === "3") {
    workoutPlan = [
        "Day 1: Full Body",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or dynamic stretches)",
        "Exercises:",
        "Bodyweight Squats: 3 sets of 12-15 reps",
        "Push-Ups: 3 sets of 10-12 reps",
        "Dumbbell Rows: 3 sets of 12 reps per side",
        "Walking Lunges: 3 sets of 10 reps per leg",
        "Plank: 3 sets of 30-45 seconds",
        "Cardio: 15 minutes of moderate-intensity cardio (e.g., jogging or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Upper Body and Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Dumbbell Bench Press: 3 sets of 10-12 reps",
        "Lat Pulldowns: 3 sets of 12 reps",
        "Dumbbell Shoulder Press: 3 sets of 10-12 reps",
        "Bicep Curls: 3 sets of 12 reps",
        "Tricep Dips (Bench or Chair): 3 sets of 12 reps",
        "Russian Twists: 3 sets of 15 reps per side",
        "Cardio: 15 minutes of HIIT (e.g., alternating 30 seconds of high-intensity work with 30 seconds of rest)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Lower Body and Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bodyweight Deadlifts: 3 sets of 12 reps",
        "Step-Ups: 3 sets of 12 reps per leg",
        "Leg Press (if available): 3 sets of 10-12 reps",
        "Calf Raises: 3 sets of 15 reps",
        "Glute Bridges: 3 sets of 12-15 reps",
        "Cardio: 20 minutes of steady-state cardio (e.g., brisk walking or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "6-12" && goals === "lose weight" && frequency === "4") {
    workoutPlan = [
        "Day 1: Full Body Strength",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or dynamic stretches)",
        "Exercises:",
        "Bodyweight Squats: 3 sets of 15 reps",
        "Dumbbell Bench Press: 3 sets of 12 reps",
        "Dumbbell Rows: 3 sets of 12 reps per side",
        "Walking Lunges: 3 sets of 12 reps per leg",
        "Plank: 3 sets of 45 seconds",
        "Cardio: 15 minutes of moderate-intensity cardio (e.g., jogging or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 2: Upper Body and Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Dumbbell Shoulder Press: 3 sets of 12 reps",
        "Lat Pulldowns: 3 sets of 12 reps",
        "Incline Dumbbell Press: 3 sets of 12 reps",
        "Bicep Curls: 3 sets of 12 reps",
        "Tricep Dips (Bench or Chair): 3 sets of 12 reps",
        "Russian Twists: 3 sets of 15 reps per side",
        "Bicycle Crunches: 3 sets of 15 reps per side",
        "Cardio: 15 minutes of HIIT (e.g., alternating 30 seconds of high-intensity work with 30 seconds of rest)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 3: Lower Body and Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bodyweight Deadlifts: 3 sets of 12 reps",
        "Leg Press: 3 sets of 12 reps",
        "Step-Ups: 3 sets of 12 reps per leg",
        "Calf Raises: 3 sets of 15 reps",
        "Glute Bridges: 3 sets of 15 reps",
        "Cardio: 20 minutes of steady-state cardio (e.g., brisk walking or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 4: Full Body and Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Push-Ups: 3 sets of 12 reps",
        "Goblet Squats: 3 sets of 15 reps",
        "Bent-Over Rows: 3 sets of 12 reps",
        "Mountain Climbers: 3 sets of 20 reps per side",
        "Cardio: 20 minutes of HIIT (e.g., alternating 30 seconds of high-intensity work with 30 seconds of rest)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Summary:",
        "Workout Days: 4 times a week",
        "Duration per Session: ~50 minutes"
    ];
} else if (experience === "6-12" && goals === "lose weight" && frequency === "5") {
    workoutPlan = [
        "Day 1: Full Body Strength",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or dynamic stretches)",
        "Exercises:",
        "Bodyweight Squats: 4 sets of 15 reps",
        "Dumbbell Bench Press: 4 sets of 12 reps",
        "Dumbbell Rows: 4 sets of 12 reps per side",
        "Walking Lunges: 4 sets of 12 reps per leg",
        "Plank: 4 sets of 45-60 seconds",
        "Cardio: 15 minutes of moderate-intensity cardio (e.g., jogging or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 2: Upper Body and Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Dumbbell Shoulder Press: 4 sets of 12 reps",
        "Lat Pulldowns: 4 sets of 12 reps",
        "Incline Dumbbell Press: 4 sets of 12 reps",
        "Bicep Curls: 4 sets of 12 reps",
        "Tricep Dips (Bench or Chair): 4 sets of 12 reps",
        "Russian Twists: 4 sets of 15 reps per side",
        "Bicycle Crunches: 4 sets of 15 reps per side",
        "Cardio: 20 minutes of HIIT (e.g., alternating 30 seconds of high-intensity work with 30 seconds of rest)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 3: Lower Body and Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bodyweight Deadlifts: 4 sets of 12 reps",
        "Leg Press: 4 sets of 12 reps",
        "Step-Ups: 4 sets of 12 reps per leg",
        "Calf Raises: 4 sets of 15 reps",
        "Glute Bridges: 4 sets of 15 reps",
        "Cardio: 25 minutes of steady-state cardio (e.g., brisk walking or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 4: Full Body and Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Kettlebell Swings: 4 sets of 15 reps",
        "Push-Ups: 4 sets of 12 reps",
        "Goblet Squats: 4 sets of 15 reps",
        "Bent-Over Rows: 4 sets of 12 reps",
        "Mountain Climbers: 4 sets of 20 reps per side",
        "Cardio: 20 minutes of HIIT (e.g., alternating 30 seconds of high-intensity work with 30 seconds of rest)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Day 5: Cardio and Core",
        "Warm-up: 5 minutes of light cardio",
        "Core Exercises:",
        "Leg Raises: 4 sets of 12-15 reps",
        "Plank with Shoulder Taps: 4 sets of 15 reps per side",
        "Side Plank: 3 sets of 30 seconds per side",
        "Flutter Kicks: 3 sets of 30 seconds",
        "Cardio: 30 minutes of steady-state cardio (e.g., jogging, cycling, or rowing)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 60 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~60 minutes"
    ];
} else if (experience === "1-2" && goals === "gain muscle" && frequency === "3") {
    workoutPlan = [
        "Day 1: Upper Body",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or dynamic stretches)",
        "Exercises:",
        "Bench Press: 4 sets of 6-8 reps",
        "Bent-Over Rows: 4 sets of 6-8 reps",
        "Overhead Press: 3 sets of 6-8 reps",
        "Weighted Dips: 3 sets of 8-10 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 2: Lower Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps",
        "Romanian Deadlifts: 4 sets of 6-8 reps",
        "Leg Press: 3 sets of 8-10 reps",
        "Calf Raises: 4 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 3: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 5-6 reps",
        "Pull-Ups: 4 sets of 6-8 reps",
        "Lunges: 3 sets of 8-10 reps per leg",
        "Plank: 3 sets of 60 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~50-55 minutes"
    ];
} else if (experience === "1-2" && goals === "gain muscle" && frequency === "4") {
    workoutPlan = [
        "Day 1: Chest and Triceps",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or dynamic stretches)",
        "Exercises:",
        "Bench Press: 4 sets of 6-8 reps",
        "Incline Dumbbell Press: 4 sets of 6-8 reps",
        "Tricep Dips: 4 sets of 8-10 reps",
        "Overhead Tricep Extension: 3 sets of 8-10 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55-60 minutes",
        "",
        "Day 2: Back and Biceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 5-6 reps",
        "Bent-Over Rows: 4 sets of 6-8 reps",
        "Lat Pulldowns: 4 sets of 8-10 reps",
        "Barbell Curls: 4 sets of 6-8 reps",
        "Hammer Curls: 3 sets of 8-10 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55-60 minutes",
        "",
        "Day 3: Legs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps",
        "Leg Press: 4 sets of 6-8 reps",
        "Romanian Deadlifts: 4 sets of 6-8 reps",
        "Calf Raises: 4 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55-60 minutes",
        "",
        "Day 4: Shoulders and Abs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Overhead Press: 4 sets of 6-8 reps",
        "Lateral Raises: 4 sets of 8-10 reps",
        "Front Raises: 3 sets of 8-10 reps",
        "Plank: 4 sets of 60 seconds",
        "Russian Twists: 4 sets of 15 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Summary:",
        "Workout Days: 4 times a week",
        "Duration per Session: ~55-60 minutes"
    ];
} else if (experience === "1-2" && goals === "gain muscle" && frequency === "5") {
    workoutPlan = [
        "Day 1: Chest and Triceps",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or dynamic stretches)",
        "Exercises:",
        "Bench Press: 4 sets of 6-8 reps",
        "Incline Dumbbell Press: 4 sets of 6-8 reps",
        "Dumbbell Flyes: 3 sets of 8-10 reps",
        "Tricep Dips: 4 sets of 8-10 reps",
        "Overhead Tricep Extension: 3 sets of 8-10 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55-60 minutes",
        "",
        "Day 2: Back and Biceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 5-6 reps",
        "Bent-Over Rows: 4 sets of 6-8 reps",
        "Lat Pulldowns: 4 sets of 8-10 reps",
        "Barbell Curls: 4 sets of 6-8 reps",
        "Hammer Curls: 3 sets of 8-10 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55-60 minutes",
        "",
        "Day 3: Legs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps",
        "Leg Press: 4 sets of 6-8 reps",
        "Romanian Deadlifts: 4 sets of 6-8 reps",
        "Lunges: 3 sets of 8-10 reps per leg",
        "Calf Raises: 4 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55-60 minutes",
        "",
        "Day 4: Shoulders and Abs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Overhead Press: 4 sets of 6-8 reps",
        "Lateral Raises: 4 sets of 8-10 reps",
        "Front Raises: 3 sets of 8-10 reps",
        "Plank: 4 sets of 60 seconds",
        "Russian Twists: 4 sets of 15 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 5: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 5-6 reps",
        "Pull-Ups: 4 sets of 6-8 reps",
        "Bench Press: 4 sets of 6-8 reps",
        "Squats: 3 sets of 6-8 reps",
        "Hanging Leg Raises: 4 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55-60 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~55-60 minutes"
    ];
} else if (experience === "1-2" && goals === "look shredded" && frequency === "3") {
    workoutPlan = [
          
        "Day 1: Full Body Power",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Barbell Deadlifts: 3 sets of 5 reps (Heavy weight, focus on explosive power)",
        "Bench Press: 3 sets of 5 reps (Heavy weight)",
        "Weighted Pull-Ups: 3 sets of 6 reps",
        "Overhead Press: 3 sets of 5 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Upper Body Strength",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Incline Dumbbell Press: 3 sets of 6 reps",
        "Bent-Over Rows: 3 sets of 5 reps",
        "Weighted Dips: 3 sets of 6 reps",
        "Face Pulls: 3 sets of 8 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Lower Body Strength & Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Barbell Squats: 3 sets of 5 reps (Heavy weight)",
        "Romanian Deadlifts: 3 sets of 5 reps",
        "Bulgarian Split Squats: 3 sets of 6 reps per leg",
        "Hanging Leg Raises: 3 sets of 10-12 reps",
        "Plank: 3 sets of 60 seconds",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "1-2" && goals === "look shredded" && frequency === "4") {
    workoutPlan = [
        "Day 1: Full Body Strength",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Barbell Squats: 3 sets of 5 reps (Heavy weight, focus on explosive power)",
        "Weighted Pull-Ups: 3 sets of 6 reps",
        "Bench Press: 3 sets of 5 reps (Heavy weight)",
        "Deadlifts: 3 sets of 4 reps (Heavy weight, focus on form)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Upper Body Power",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Incline Barbell Press: 3 sets of 6 reps",
        "Bent-Over Rows: 3 sets of 5 reps",
        "Dumbbell Shoulder Press: 3 sets of 6 reps",
        "Weighted Dips: 3 sets of 6 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Lower Body Power",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Sumo Deadlifts: 3 sets of 5 reps (Heavy weight)",
        "Leg Press: 3 sets of 6 reps",
        "Romanian Deadlifts: 3 sets of 5 reps",
        "Bulgarian Split Squats: 3 sets of 6 reps per leg",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 4: High-Intensity Core & Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Core Exercises:",
        "Hanging Leg Raises: 3 sets of 10-12 reps",
        "Weighted Russian Twists: 3 sets of 15 reps per side",
        "Plank with Weighted Hold: 3 sets of 60 seconds",
        "Cardio: 20 minutes of HIIT (e.g., sprint intervals, 30 seconds on, 30 seconds off)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes"
    ];
} else if (experience === "1-2" && goals === "look shredded" && frequency === "5") {
    workoutPlan = [
        "Day 1: Upper Body Strength",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 3 sets of 5 reps (Heavy weight)",
        "Pull-Ups: 3 sets of 6 reps",
        "Overhead Press: 3 sets of 5 reps",
        "Dumbbell Rows: 3 sets of 6 reps per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Lower Body Power",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Barbell Squats: 3 sets of 5 reps (Heavy weight)",
        "Deadlifts: 3 sets of 5 reps",
        "Lunges: 3 sets of 6 reps per leg",
        "Calf Raises: 3 sets of 12 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Core and Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Hanging Leg Raises: 3 sets of 10-12 reps",
        "Russian Twists: 3 sets of 15 reps per side",
        "Plank: 3 sets of 60 seconds",
        "Mountain Climbers: 3 sets of 20 reps per side",
        "Cardio: 20 minutes of HIIT (e.g., sprints, cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 4: Upper Body Hypertrophy",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Incline Dumbbell Press: 3 sets of 6 reps",
        "Weighted Dips: 3 sets of 6 reps",
        "Face Pulls: 3 sets of 8 reps",
        "Bicep Curls: 3 sets of 8 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 5: Lower Body and Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Romanian Deadlifts: 3 sets of 5 reps",
        "Bulgarian Split Squats: 3 sets of 6 reps per leg",
        "Leg Press: 3 sets of 6 reps",
        "Side Plank: 3 sets of 30 seconds per side",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "1-2" && goals === "lose weight" && frequency === "3") {
    workoutPlan = [
        "Day 1: Full Body Strength and Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 3 sets of 5 reps (Heavy weight)",
        "Push-Ups: 3 sets of 10 reps (Add weight if possible)",
        "Goblet Squats: 3 sets of 6 reps",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Cardio: 15 minutes of HIIT (e.g., sprints or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Upper Body Strength and Cardio",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Bench Press: 3 sets of 5 reps (Heavy weight)",
        "Bent-Over Rows: 3 sets of 5 reps",
        "Overhead Press: 3 sets of 5 reps",
        "Battle Ropes: 3 sets of 20 seconds (intense)",
        "Cardio: 20 minutes of steady-state cardio (e.g., brisk walking or moderate cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Lower Body Power and Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Barbell Squats: 3 sets of 5 reps (Heavy weight)",
        "Lunges: 3 sets of 6 reps per leg",
        "Plank with Leg Lift: 3 sets of 30 seconds per side",
        "Mountain Climbers: 3 sets of 20 reps per side",
        "Cardio: 15 minutes of HIIT (e.g., sprint intervals)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "1-2" && goals === "lose weight" && frequency === "4") {
    workoutPlan = [
        "Day 1: Full Body Strength and Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 3 sets of 5 reps (Heavy weight)",
        "Push-Ups: 3 sets of 10 reps (Add weight if possible)",
        "Goblet Squats: 3 sets of 6 reps",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Cardio: 15 minutes of HIIT (e.g., sprints or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Upper Body Strength and Core",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Bench Press: 3 sets of 5 reps (Heavy weight)",
        "Bent-Over Rows: 3 sets of 5 reps",
        "Overhead Press: 3 sets of 5 reps",
        "Russian Twists: 3 sets of 15 reps per side",
        "Cardio: 20 minutes of steady-state cardio (e.g., brisk walking or moderate cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Lower Body Power",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Barbell Squats: 3 sets of 5 reps (Heavy weight)",
        "Lunges: 3 sets of 6 reps per leg",
        "Leg Press: 3 sets of 5 reps (Heavy weight)",
        "Calf Raises: 3 sets of 12 reps",
        "Cardio: 15 minutes of HIIT (e.g., sprint intervals)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 4: Full Body and Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-Ups: 3 sets of 5 reps (Add weight if possible)",
        "Dumbbell Shoulder Press: 3 sets of 6 reps",
        "Walking Lunges: 3 sets of 6 reps per leg",
        "Mountain Climbers: 3 sets of 20 reps per side",
        "Cardio: 20 minutes of HIIT (e.g., alternating 30 seconds of high-intensity work with 30 seconds of rest)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        "Workout Days: 4 times a week",
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "1-2" && goals === "lose weight" && frequency === "5") {
    workoutPlan = [
        "Day 1: Full Body Strength and Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 3 sets of 5 reps (Heavy weight)",
        "Push-Ups: 3 sets of 10 reps (Add weight if possible)",
        "Goblet Squats: 3 sets of 6 reps",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Cardio: 15 minutes of HIIT (e.g., sprints or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Upper Body Strength and Core",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Bench Press: 3 sets of 5 reps (Heavy weight)",
        "Bent-Over Rows: 3 sets of 5 reps",
        "Overhead Press: 3 sets of 5 reps",
        "Russian Twists: 3 sets of 15 reps per side",
        "Cardio: 20 minutes of steady-state cardio (e.g., brisk walking or moderate cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Lower Body Power",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Barbell Squats: 3 sets of 5 reps (Heavy weight)",
        "Lunges: 3 sets of 6 reps per leg",
        "Leg Press: 3 sets of 5 reps (Heavy weight)",
        "Calf Raises: 3 sets of 12 reps",
        "Cardio: 15 minutes of HIIT (e.g., sprint intervals)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 4: Upper Body Power and Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-Ups: 3 sets of 5 reps (Add weight if possible)",
        "Dumbbell Bench Press: 3 sets of 6 reps",
        "Dumbbell Rows: 3 sets of 6 reps per side",
        "Plank: 3 sets of 45-60 seconds",
        "Cardio: 20 minutes of steady-state cardio (e.g., brisk walking or moderate cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 5: Full Body and Cardio",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Kettlebell Swings: 3 sets of 15 reps",
        "Burpees: 3 sets of 10 reps",
        "Goblet Squats: 3 sets of 10 reps",
        "Mountain Climbers: 3 sets of 20 reps per side",
        "Cardio: 20 minutes of HIIT (e.g., alternating 30 seconds of high-intensity work with 30 seconds of rest)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "2+" && goals === "gain muscle" && frequency === "3") {
    workoutPlan = [
        "Day 1: Upper Body Push",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 3 sets of 6-8 reps (Last set to failure)",
        "Incline Dumbbell Press: 3 sets of 8-10 reps (Drop set on last set)",
        "Overhead Dumbbell Press: 3 sets of 8-10 reps (Last set to failure)",
        "Tricep Dips: 3 sets of 8-10 reps (Bodyweight or weighted, last set to failure)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Lower Body",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Barbell Squats: 3 sets of 6-8 reps (Last set to failure)",
        "Deadlifts: 3 sets of 6-8 reps (Last set to failure)",
        "Leg Press: 3 sets of 8-10 reps (Drop set on last set)",
        "Walking Lunges: 3 sets of 10 reps per leg (Heavy weight)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Upper Body Pull",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-Ups: 3 sets of 6-8 reps (Weighted if possible, last set to failure)",
        "Bent-Over Rows: 3 sets of 6-8 reps (Drop set on last set)",
        "Single-Arm Dumbbell Rows: 3 sets of 8-10 reps per side (Last set to failure)",
        "Barbell Curls: 3 sets of 8-10 reps (Drop set on last set)",
        "Face Pulls: 3 sets of 12-15 reps (Heavy weight)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "2+" && goals === "gain muscle" && frequency === "4") {
    workoutPlan = [
        "Day 1: Upper Body Push",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 3 sets of 6-8 reps (Last set to failure)",
        "Incline Dumbbell Press: 3 sets of 8-10 reps (Drop set on last set)",
        "Overhead Dumbbell Press: 3 sets of 8-10 reps (Last set to failure)",
        "Tricep Dips: 3 sets of 8-10 reps (Bodyweight or weighted, last set to failure)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 2: Lower Body",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Barbell Squats: 3 sets of 6-8 reps (Last set to failure)",
        "Deadlifts: 3 sets of 6-8 reps (Last set to failure)",
        "Leg Press: 3 sets of 8-10 reps (Drop set on last set)",
        "Walking Lunges: 3 sets of 10 reps per leg (Heavy weight)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 3: Upper Body Pull",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Pull-Ups: 3 sets of 6-8 reps (Weighted if possible, last set to failure)",
        "Bent-Over Rows: 3 sets of 6-8 reps (Drop set on last set)",
        "Single-Arm Dumbbell Rows: 3 sets of 8-10 reps per side (Last set to failure)",
        "Barbell Curls: 3 sets of 8-10 reps (Drop set on last set)",
        "Face Pulls: 3 sets of 12-15 reps (Heavy weight)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Day 4: Full Body",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 3 sets of 6-8 reps (Last set to failure)",
        "Bench Press: 3 sets of 6-8 reps (Drop set on last set)",
        "Barbell Rows: 3 sets of 8-10 reps (Last set to failure)",
        "Overhead Press: 3 sets of 8-10 reps (Drop set on last set)",
        "Hanging Leg Raises: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 45-50 minutes",
        "",
        "Summary:",
        "Workout Days: 4 times a week",
        "Duration per Session: ~45-50 minutes"
    ];
} else if (experience === "2+" && goals === "gain muscle" && frequency === "5") {
    workoutPlan = [
        "Day 1: Chest and Triceps",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Bench Press: 4 sets of 6-8 reps (Last set to failure)",
        "Incline Dumbbell Press: 3 sets of 8-10 reps (Drop set on last set)",
        "Dumbbell Flyes: 3 sets of 10-12 reps (Last set to failure)",
        "Tricep Dips: 3 sets of 8-10 reps (Bodyweight or weighted, last set to failure)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 2: Back and Biceps",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Deadlifts: 4 sets of 6-8 reps (Last set to failure)",
        "Pull-Ups: 3 sets of 6-8 reps (Weighted if possible, last set to failure)",
        "Bent-Over Rows: 3 sets of 8-10 reps (Drop set on last set)",
        "Barbell Curls: 3 sets of 8-10 reps (Last set to failure)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 3: Legs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps (Last set to failure)",
        "Leg Press: 3 sets of 8-10 reps (Drop set on last set)",
        "Romanian Deadlifts: 3 sets of 8-10 reps (Last set to failure)",
        "Calf Raises: 4 sets of 12-15 reps (Last set to failure)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 4: Shoulders and Abs",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Overhead Press: 4 sets of 6-8 reps (Last set to failure)",
        "Lateral Raises: 3 sets of 10-12 reps (Drop set on last set)",
        "Front Raises: 3 sets of 10-12 reps (Last set to failure)",
        "Plank: 4 sets of 45-60 seconds",
        "Hanging Leg Raises: 3 sets of 12-15 reps",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 5: Full Body (High Intensity)",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 3 sets of 6-8 reps (Last set to failure)",
        "Bench Press: 3 sets of 6-8 reps (Drop set on last set)",
        "Pull-Ups: 3 sets of 6-8 reps (Weighted if possible, last set to failure)",
        "Squats: 3 sets of 6-8 reps (Last set to failure)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~50 minutes"
    ];
} else if (experience === "2+" && goals === "look shredded" && frequency === "3") {
    workoutPlan = [
        "Day 1: Full Body Circuit",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 3 sets of 6-8 reps (Last set to failure)",
        "Pull-Ups: 3 sets of 6-8 reps (Weighted if possible, last set to failure)",
        "Bench Press: 3 sets of 6-8 reps (Drop set on last set)",
        "Kettlebell Swings: 3 sets of 12-15 reps (Last set to failure)",
        "Plank: 3 sets of 1 minute",
        "Cardio: 15 minutes of high-intensity interval training (HIIT)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 2: Upper Body Focus",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Overhead Press: 3 sets of 6-8 reps (Last set to failure)",
        "Incline Dumbbell Press: 3 sets of 8-10 reps (Drop set on last set)",
        "Bent-Over Rows: 3 sets of 8-10 reps (Last set to failure)",
        "Bicep Curls: 3 sets of 8-10 reps (Drop set on last set)",
        "Tricep Dips: 3 sets of 10-12 reps (Last set to failure)",
        "Cardio: 15 minutes of HIIT (e.g., 30 seconds sprint, 30 seconds rest)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50 minutes",
        "",
        "Day 3: Lower Body and Core",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 3 sets of 6-8 reps (Last set to failure)",
        "Romanian Deadlifts: 3 sets of 8-10 reps (Drop set on last set)",
        "Leg Press: 3 sets of 8-10 reps (Last set to failure)",
        "Hanging Leg Raises: 3 sets of 12-15 reps",
        "Russian Twists: 3 sets of 20 reps per side",
        "Cardio: 20 minutes of steady-state cardio (e.g., cycling or brisk walking)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~50-55 minutes"
    ];
} else if (experience === "2+" && goals === "look shredded" && frequency === "4") {
    workoutPlan = [
        "Day 1: Full Body Power",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 5-7 reps (Last set to failure)",
        "Push-Ups: 4 sets of 12-15 reps (Weighted if possible, last set to failure)",
        "Pull-Ups: 4 sets of 6-8 reps (Weighted if possible, last set to failure)",
        "Kettlebell Swings: 4 sets of 12-15 reps (Last set to failure)",
        "Plank: 4 sets of 1 minute",
        "Cardio: 15 minutes of HIIT (e.g., sprinting or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 2: Upper Body Strength",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Incline Bench Press: 4 sets of 6-8 reps (Last set to failure)",
        "Overhead Press: 4 sets of 6-8 reps (Drop set on last set)",
        "Bent-Over Rows: 4 sets of 8-10 reps (Last set to failure)",
        "Bicep Curls: 4 sets of 8-10 reps (Drop set on last set)",
        "Tricep Dips: 4 sets of 10-12 reps (Last set to failure)",
        "Cardio: 20 minutes of steady-state cardio (e.g., jogging)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 3: Lower Body Focus",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps (Last set to failure)",
        "Leg Press: 4 sets of 8-10 reps (Drop set on last set)",
        "Romanian Deadlifts: 4 sets of 8-10 reps (Last set to failure)",
        "Lunges: 4 sets of 12 reps per leg (Last set to failure)",
        "Cardio: 15 minutes of HIIT (e.g., sprint intervals)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 4: Core and Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Core Exercises:",
        "Hanging Leg Raises: 4 sets of 12-15 reps (Last set to failure)",
        "Russian Twists: 4 sets of 20 reps per side",
        "Side Planks: 4 sets of 30 seconds per side",
        "Bicycle Crunches: 4 sets of 20 reps per side",
        "Cardio: 25 minutes of steady-state cardio (e.g., brisk walking or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Summary:",
        "Workout Days: 4 times a week",
        "Duration per Session: ~55 minutes"
    ];
} else if (experience === "2+" && goals === "look shredded" && frequency === "5") {
    workoutPlan = [
        "Day 1: Full Body Power",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Deadlifts: 4 sets of 5-7 reps (Perform the last set till failure)",
        "Push-Ups: 4 sets of 12-15 reps (Consider adding weight; last set till failure)",
        "Pull-Ups: 4 sets of 6-8 reps (Weighted if possible; last set till failure)",
        "Kettlebell Swings: 4 sets of 12-15 reps (Complete the last set till failure)",
        "Plank: 4 sets of 1 minute",
        "Cardio: 15 minutes of HIIT (e.g., sprinting or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 2: Upper Body Strength",
        "Warm-up: 5 minutes of dynamic stretching",
        "Exercises:",
        "Incline Bench Press: 4 sets of 6-8 reps (Execute a drop set on the last set)",
        "Overhead Press: 4 sets of 6-8 reps (Last set to failure)",
        "Bent-Over Rows: 4 sets of 8-10 reps (Last set to failure)",
        "Bicep Curls: 4 sets of 8-10 reps (Drop set on the last set)",
        "Tricep Dips: 4 sets of 10-12 reps (Last set to failure)",
        "Cardio: 20 minutes of steady-state cardio (e.g., jogging)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 3: Lower Body Focus",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps (Perform the last set till failure)",
        "Leg Press: 4 sets of 8-10 reps (Execute a drop set on the last set)",
        "Romanian Deadlifts: 4 sets of 8-10 reps (Last set to failure)",
        "Lunges: 4 sets of 12 reps per leg (Last set to failure)",
        "Cardio: 15 minutes of HIIT (e.g., sprint intervals)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 4: Core and Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Core Exercises:",
        "Hanging Leg Raises: 4 sets of 12-15 reps (Last set to failure)",
        "Russian Twists: 4 sets of 20 reps per side",
        "Side Planks: 4 sets of 30 seconds per side",
        "Bicycle Crunches: 4 sets of 20 reps per side",
        "Cardio: 25 minutes of steady-state cardio (e.g., brisk walking or cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Day 5: Full Body Intensity",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Barbell Rows: 4 sets of 8-10 reps (Last set to failure)",
        "Dumbbell Chest Press: 4 sets of 6-8 reps (Execute a drop set on the last set)",
        "Leg Curls: 4 sets of 8-10 reps (Last set to failure)",
        "Lateral Raises: 4 sets of 12-15 reps (Last set to failure)",
        "Burpees: 4 sets of 15 reps",
        "Cardio: 20 minutes of HIIT (e.g., alternating high-intensity intervals with active recovery)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 55 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~55 minutes"
    ];
} else if (experience === "2+" && goals === "lose weight" && frequency === "3") {
    workoutPlan = [
        "Day 1: Full Body Circuit",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jumping jacks)",
        "Exercises:",
        "Deadlifts: 4 sets of 6-8 reps (Perform the last set till failure)",
        "Push-Ups: 4 sets of 12-15 reps (Last set to failure, drop set with knee push-ups if needed)",
        "Kettlebell Swings: 4 sets of 12-15 reps (Last set till failure)",
        "Mountain Climbers: 4 sets of 20 reps per side",
        "Burpees: 4 sets of 12 reps (Last set to failure)",
        "Cardio: 20 minutes of HIIT (e.g., alternating 30 seconds of sprinting with 30 seconds of walking)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 2: Upper Body & Core",
        "Warm-up: 5 minutes of dynamic stretches",
        "Exercises:",
        "Incline Bench Press: 4 sets of 8-10 reps (Perform a drop set on the last set)",
        "Bent-Over Rows: 4 sets of 8-10 reps (Last set to failure)",
        "Shoulder Press: 4 sets of 6-8 reps (Last set till failure)",
        "Bicep Curls: 4 sets of 8-10 reps (Drop set on the last set)",
        "Russian Twists: 4 sets of 15 reps per side",
        "Plank: 4 sets of 1 minute",
        "Cardio: 15 minutes of moderate-intensity cardio (e.g., cycling or rowing)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 3: Lower Body & Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps (Last set till failure)",
        "Lunges: 4 sets of 12 reps per leg (Last set to failure)",
        "Leg Press: 4 sets of 8-10 reps (Drop set on the last set)",
        "Glute Bridges: 4 sets of 12-15 reps (Last set till failure)",
        "Box Jumps: 4 sets of 10-12 reps",
        "Cardio: 20 minutes of HIIT (e.g., sprint intervals or high-intensity cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Summary:",
        "Workout Days: 3 times a week",
        "Duration per Session: ~50-55 minutes"
    ];
} else if (experience === "2+" && goals === "lose weight" && frequency === "4") {
    workoutPlan = [
        "Day 1: Full Body Circuit",
        "Warm-up: 5 minutes of light cardio (e.g., brisk walking or jumping jacks)",
        "Exercises:",
        "Deadlifts: 4 sets of 6-8 reps (Last set till failure)",
        "Push-Ups: 4 sets of 12-15 reps (Last set to failure, drop set with knee push-ups if needed)",
        "Kettlebell Swings: 4 sets of 12-15 reps (Last set till failure)",
        "Burpees: 4 sets of 12 reps (Last set to failure)",
        "Cardio: 20 minutes of HIIT (e.g., alternating 30 seconds of sprinting with 30 seconds of walking)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 2: Upper Body & Core",
        "Warm-up: 5 minutes of dynamic stretches",
        "Exercises:",
        "Incline Bench Press: 4 sets of 8-10 reps (Drop set on the last set)",
        "Bent-Over Rows: 4 sets of 8-10 reps (Last set to failure)",
        "Shoulder Press: 4 sets of 6-8 reps (Last set till failure)",
        "Bicep Curls: 4 sets of 8-10 reps (Drop set on the last set)",
        "Russian Twists: 4 sets of 15 reps per side",
        "Plank: 4 sets of 1 minute",
        "Cardio: 15 minutes of moderate-intensity cardio (e.g., cycling or rowing)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 3: Lower Body & Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps (Last set till failure)",
        "Lunges: 4 sets of 12 reps per leg (Last set to failure)",
        "Leg Press: 4 sets of 8-10 reps (Drop set on the last set)",
        "Glute Bridges: 4 sets of 12-15 reps (Last set till failure)",
        "Box Jumps: 4 sets of 10-12 reps",
        "Cardio: 20 minutes of HIIT (e.g., sprint intervals or high-intensity cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 4: Full Body Conditioning",
        "Warm-up: 5 minutes of light cardio (e.g., jumping rope or high knees)",
        "Exercises:",
        "Thrusters: 4 sets of 8-10 reps (Last set till failure)",
        "Renegade Rows: 4 sets of 10-12 reps per side (Last set to failure)",
        "Dumbbell Snatches: 4 sets of 8-10 reps per side (Drop set on the last set)",
        "Mountain Climbers: 4 sets of 30 seconds",
        "High Knees: 4 sets of 30 seconds",
        "Cardio: 20 minutes of steady-state cardio (e.g., jogging or brisk walking)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Summary:",
        "Workout Days: 4 times a week",
        "Duration per Session: ~50-55 minutes"
    ];
} else if (experience === "2+" && goals === "lose weight" && frequency === "5") {
    workoutPlan = [
        "Day 1: Full Body Strength",
        "Warm-up: 5 minutes of light cardio (e.g., jumping jacks or brisk walking)",
        "Exercises:",
        "Deadlifts: 4 sets of 6-8 reps (Last set till failure)",
        "Push-Ups: 4 sets of 12-15 reps (Last set to failure, drop set with knee push-ups if needed)",
        "Dumbbell Rows: 4 sets of 8-10 reps per side (Drop set on the last set)",
        "Burpees: 4 sets of 12 reps",
        "Cardio: 15 minutes of moderate-intensity cardio (e.g., cycling or rowing)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 2: Upper Body & Core",
        "Warm-up: 5 minutes of dynamic stretches",
        "Exercises:",
        "Incline Bench Press: 4 sets of 8-10 reps (Drop set on the last set)",
        "Bent-Over Rows: 4 sets of 8-10 reps (Last set to failure)",
        "Shoulder Press: 4 sets of 6-8 reps (Last set till failure)",
        "Bicep Curls: 4 sets of 8-10 reps (Drop set on the last set)",
        "Russian Twists: 4 sets of 15 reps per side",
        "Plank: 4 sets of 1 minute",
        "Cardio: 15 minutes of moderate-intensity cardio (e.g., elliptical or rowing)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 3: Lower Body & Conditioning",
        "Warm-up: 5 minutes of light cardio",
        "Exercises:",
        "Squats: 4 sets of 6-8 reps (Last set till failure)",
        "Lunges: 4 sets of 12 reps per leg (Drop set on the last set)",
        "Leg Press: 4 sets of 8-10 reps (Drop set on the last set)",
        "Glute Bridges: 4 sets of 12-15 reps (Last set till failure)",
        "Box Jumps: 4 sets of 10-12 reps",
        "Cardio: 20 minutes of HIIT (e.g., sprint intervals or high-intensity cycling)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 4: Upper Body & Core",
        "Warm-up: 5 minutes of light cardio (e.g., high knees or arm circles)",
        "Exercises:",
        "Pull-Ups: 4 sets of 6-8 reps (Last set till failure)",
        "Dumbbell Bench Press: 4 sets of 8-10 reps (Drop set on the last set)",
        "Seated Shoulder Press: 4 sets of 8-10 reps (Last set till failure)",
        "Tricep Dips: 4 sets of 12 reps (Drop set on the last set)",
        "Leg Raises: 4 sets of 12-15 reps",
        "Bicycle Crunches: 4 sets of 15 reps per side",
        "Cardio: 20 minutes of moderate-intensity cardio (e.g., cycling or jogging)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Day 5: Full Body Conditioning",
        "Warm-up: 5 minutes of light cardio (e.g., jumping rope or jogging)",
        "Exercises:",
        "Kettlebell Swings: 4 sets of 15 reps (Last set till failure)",
        "Goblet Squats: 4 sets of 12-15 reps (Drop set on the last set)",
        "Renegade Rows: 4 sets of 10-12 reps per side",
        "Mountain Climbers: 4 sets of 30 seconds (Last set till failure)",
        "High Knees: 4 sets of 30 seconds",
        "Cardio: 20 minutes of steady-state cardio (e.g., jogging or rowing)",
        "Cool Down: 5 minutes of stretching",
        "Duration: Approximately 50-55 minutes",
        "",
        "Summary:",
        "Workout Days: 5 times a week",
        "Duration per Session: ~50-55 minutes"
    ];
}
     else {
            // Default or other plans go here
            workoutPlan = ["No specific workout plan available for the selected criteria."];
        }

        console.log("Workout Plan Generated:", workoutPlan);

        // Clear previous plan
        planDetails.innerHTML = "";

        // Show control buttons
        controlButtons.classList.remove("hidden");

        // Initialize workout plan generation
        stopGeneration = false;
        isGenerating = true;
        currentStep = 0;

        // Show the workout plan div
        workoutPlanDiv.classList.remove("hidden");

        // Start generating the workout plan with typing effect
        generateWorkoutPlanWithTypingEffect();
    });

    function generateWorkoutPlanWithTypingEffect() {
        if (stopGeneration || !isGenerating) return;

        if (currentStep < workoutPlan.length) {
            typeEffect(workoutPlan[currentStep], 0, function () {
                planDetails.innerHTML += "<br>"; // Move to the next line
                currentStep++;
                setTimeout(generateWorkoutPlanWithTypingEffect, 300); // Delay before the next step
            });
        } else {
            console.log("Finished generating workout plan.");
            isGenerating = false;
            controlButtons.classList.add("hidden");
        }
    }

    function typeEffect(text, index, callback) {
        if (index < text.length) {
            planDetails.innerHTML += text.charAt(index);
            setTimeout(function () {
                typeEffect(text, index + 1, callback);
            }, 20); // Adjust typing speed here
        } else if (callback) {
            callback();
        }
    }

    // Stop button functionality
    stopButton.addEventListener("click", function () {
        console.log("Stopping generation.");
        stopGeneration = true;
        isGenerating = false;
        resumeButton.style.display = "block";
    });

    // Resume button functionality
    resumeButton.addEventListener("click", function () {
        if (stopGeneration) {
            console.log("Resuming generation.");
            stopGeneration = false;
            isGenerating = true;
            generateWorkoutPlanWithTypingEffect();
            resumeButton.style.display = "none";
        }
    });

    // Clear button functionality
    clearButton.addEventListener("click", function () {
        console.log("Clearing workout plan.");
        planDetails.innerHTML = "";
        workoutPlanDiv.classList.add("hidden");
        controlButtons.classList.add("hidden");
        resumeButton.style.display = "none";
    });
});